-- All test changes are rolled back. Run against the warehouse project as postgres.
begin;
do $$
declare s jsonb; s2 jsonb; r integer; op uuid; id1 text; id2 text; blocked boolean; i integer;
begin
  assert public.sklad_login(null,'SQL test')->>'error' is not null, 'Null PIN rejected';
  assert public.sklad_login('0000',null)->>'error' is not null, 'Null actor rejected';
  insert into sklad_private.sessions values(encode(extensions.digest('warehouse-transaction-test','sha256'),'hex'),'SQL test',now()+interval '1 hour');
  blocked:=false;
  begin perform public.sklad_read('invalid'); exception when others then blocked:=sqlerrm='AUTH'; end;
  assert blocked, 'Unauthorized read must fail';
  s:=public.sklad_read('warehouse-transaction-test');
  r:=(s->>'revision')::integer;
  id1:=s->'items'->0->>'id'; id2:=s->'items'->1->>'id';
  op:=gen_random_uuid();
  s:=public.sklad_command('warehouse-transaction-test',op,r,jsonb_build_object('kind','inventory','warehouse','adler','note','Test inventory','lines',jsonb_build_array(jsonb_build_object('id',id1,'quantity',10)))); r:=r+1;
  assert (s->'items'->0->>'adler')::numeric=10, 'Inventory sets actual';
  s2:=public.sklad_command('warehouse-transaction-test',op,r-1,jsonb_build_object('kind','inventory'));
  assert s2=s, 'Retry is idempotent';
  blocked:=false;
  begin perform public.sklad_command('warehouse-transaction-test',gen_random_uuid(),r-1,jsonb_build_object('kind','inventory')); exception when others then blocked:=sqlerrm='CONFLICT'; end;
  assert blocked, 'Stale revision rejected';
  s:=public.sklad_command('warehouse-transaction-test',gen_random_uuid(),r,jsonb_build_object('kind','inventory','warehouse','sochi','note','Test inventory','lines',jsonb_build_array(jsonb_build_object('id',id1,'quantity',0)))); r:=r+1;
  s:=public.sklad_command('warehouse-transaction-test',gen_random_uuid(),r,jsonb_build_object('kind','transfer','warehouse','adler','note','Test transfer','lines',jsonb_build_array(jsonb_build_object('id',id1,'quantity',3)))); r:=r+1;
  assert (s->'items'->0->>'adler')::numeric=7 and (s->'items'->0->>'sochi')::numeric=3, 'Transfer conserves quantities';
  blocked:=false;
  begin perform public.sklad_command('warehouse-transaction-test',gen_random_uuid(),r,jsonb_build_object('kind','writeoff','warehouse','adler','note','Test invalid','lines',jsonb_build_array(jsonb_build_object('id',id1,'quantity',8)))); exception when others then blocked:=sqlerrm='STOCK'; end;
  assert blocked, 'Negative stock rejected';
  assert public.sklad_read('warehouse-transaction-test')=s, 'Failed operation must not change data';
  blocked:=false;
  begin perform public.sklad_command('warehouse-transaction-test',gen_random_uuid(),r,jsonb_build_object('kind','transfer','warehouse','adler','note','Test unknown','lines',jsonb_build_array(jsonb_build_object('id',id2,'quantity',1)))); exception when others then blocked:=sqlerrm='UNKNOWN'; end;
  assert blocked, 'Unknown destination rejected';
  s:=public.sklad_command('warehouse-transaction-test',gen_random_uuid(),r,jsonb_build_object('kind','receipt','warehouse','adler','note','Test receipt','lines',jsonb_build_array(jsonb_build_object('id',id1,'quantity',2)))); r:=r+1;
  assert (s->'items'->0->>'adler')::numeric=9, 'Receipt adds stock';
  s:=public.sklad_command('warehouse-transaction-test',gen_random_uuid(),r,jsonb_build_object('kind','writeoff','warehouse','adler','note','Test writeoff','lines',jsonb_build_array(jsonb_build_object('id',id1,'quantity',1)))); r:=r+1;
  assert (s->'items'->0->>'adler')::numeric=8, 'Writeoff subtracts stock';
  s:=public.sklad_command('warehouse-transaction-test',gen_random_uuid(),r,jsonb_build_object('kind','target','warehouse','adler','note','Test target','lines',jsonb_build_array(jsonb_build_object('id',id1,'quantity',15)))); r:=r+1;
  assert (s->'items'->0->>'adler')::numeric=8 and (s->'items'->0->>'targetAdler')::numeric=15, 'Target does not change actual';
  blocked:=false;
  begin perform public.sklad_command('warehouse-transaction-test',gen_random_uuid(),r,jsonb_build_object('kind','receipt','warehouse','adler','note','Test fractional','lines',jsonb_build_array(jsonb_build_object('id',id1,'quantity',0.5)))); exception when others then blocked:=sqlerrm='INVALID'; end;
  assert blocked, 'Fractional pieces rejected';
  blocked:=false;
  begin perform public.sklad_command('warehouse-transaction-test',gen_random_uuid(),r,jsonb_build_object('kind','inventory','warehouse','adler','note','Test atomic','lines',jsonb_build_array(jsonb_build_object('id',id1,'quantity',99),jsonb_build_object('id','missing','quantity',1)))); exception when others then blocked:=sqlerrm='MISSING'; end;
  assert blocked and public.sklad_read('warehouse-transaction-test')=s, 'Batch is atomic';
  s:=public.sklad_command('warehouse-transaction-test',gen_random_uuid(),r,jsonb_build_object('kind','item','note','Test item','item',jsonb_build_object('name','SQL test item','category','Химия','unit','л'))); r:=r+1;
  i:=jsonb_array_length(s->'items')-1;
  assert s->'items'->i->>'adler' is null, 'New stock is unknown';
  id2:=s->'items'->i->>'id';
  s:=public.sklad_command('warehouse-transaction-test',gen_random_uuid(),r,jsonb_build_object('kind','inventory','warehouse','adler','note','Test decimal','lines',jsonb_build_array(jsonb_build_object('id',id2,'quantity',1.125))));
  assert (s->'items'->i->>'adler')::numeric=1.125, 'Decimal liquids supported';
  perform public.sklad_logout('warehouse-transaction-test');
  blocked:=false;
  begin perform public.sklad_read('warehouse-transaction-test'); exception when others then blocked:=sqlerrm='AUTH'; end;
  assert blocked, 'Logout invalidates session';
end $$;
select 'All warehouse transaction checks passed; test changes rolled back' as result;
rollback;
