import { fireEvent, render, screen, waitFor, cleanup } from '@testing-library/react';
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { HelmetProvider } from 'react-helmet-async';
import Warehouse from '@/pages/Warehouse';
import { rpc, readStock, WarehouseError } from '@/features/warehouse/api';
vi.mock('@/features/warehouse/api',async()=>{const actual=await vi.importActual('@/features/warehouse/api');return {...actual,rpc:vi.fn(),readStock:vi.fn()};});
const data={revision:0,items:[{id:'bucket',name:'Ведро',category:'Инвентарь',unit:'шт',note:'',adler:7,sochi:null,targetAdler:10,targetSochi:3}],history:[]};
const mount=()=>render(<HelmetProvider><Warehouse/></HelmetProvider>);
beforeEach(()=>{sessionStorage.clear();vi.clearAllMocks();vi.mocked(readStock).mockResolvedValue(data);});
afterEach(cleanup);
it('does not fetch or render private stock before login',()=>{mount();expect(readStock).not.toHaveBeenCalled();expect(screen.queryByText('Ведро')).not.toBeInTheDocument();});
it('sends credentials to server and shows rejected login',async()=>{vi.mocked(rpc).mockResolvedValue({error:'Неверный код доступа.'});mount();fireEvent.change(screen.getByLabelText('Ваше имя'),{target:{value:'Тест'}});fireEvent.change(screen.getByLabelText('Код доступа'),{target:{value:'0000'}});fireEvent.click(screen.getByText('Открыть склад →'));expect(await screen.findByRole('alert')).toHaveTextContent('Неверный код');expect(readStock).not.toHaveBeenCalled();});
it('keeps unknown Sochi stock out of purchasing list',async()=>{sessionStorage.setItem('sklad-session',JSON.stringify({token:'test',actor:'Тест'}));mount();await screen.findByText('Ведро');fireEvent.click(screen.getByRole('button',{name:'Сочи'}));fireEvent.click(screen.getByText('К пополнению'));expect(screen.queryByText('Ведро')).not.toBeInTheDocument();expect(screen.getByText('По выбранным условиям позиций нет.')).toBeInTheDocument();});
it('retries an uncertain write with exactly the same operation id',async()=>{sessionStorage.setItem('sklad-session',JSON.stringify({token:'test',actor:'Тест'}));vi.mocked(rpc).mockRejectedValueOnce(new WarehouseError('Нет связи')).mockResolvedValueOnce({...data,revision:1});mount();await screen.findByText('Ведро');fireEvent.click(screen.getByRole('button',{name:'Поступление: Ведро'}));fireEvent.change(screen.getByLabelText('Количество: Ведро'),{target:{value:'2'}});fireEvent.change(screen.getByLabelText('Основание / комментарий'),{target:{value:'Закупка'}});fireEvent.click(screen.getByText('Провести операцию'));await screen.findByText('Проверить / повторить');const first=vi.mocked(rpc).mock.calls[0];fireEvent.click(screen.getByText('Проверить / повторить'));await waitFor(()=>expect(rpc).toHaveBeenCalledTimes(2));expect(vi.mocked(rpc).mock.calls[1]).toEqual(first);await screen.findByText('Операция проведена. Остатки сохранены на сервере.');});
it('recovers an uncertain operation after remount without a new id',async()=>{sessionStorage.setItem('sklad-session',JSON.stringify({token:'test',actor:'Тест'}));const p={id:'recovery-id',revision:0,command:{kind:'receipt',warehouse:'adler',note:'Закупка',lines:[{id:'bucket',quantity:2}]}};sessionStorage.setItem('sklad-pending',JSON.stringify(p));vi.mocked(rpc).mockResolvedValue({...data,revision:1});mount();await screen.findByText('Ведро');fireEvent.click(screen.getByText('Проверить предыдущую операцию'));await screen.findByText('Результат предыдущей операции подтверждён. Остатки сохранены.');expect(rpc).toHaveBeenCalledWith('command',{p_token:'test',p_id:p.id,p_revision:0,p_command:p.command});expect(sessionStorage.getItem('sklad-pending')).toBeNull();});
it('shows the standard separately from the counted quantity and can filter equipment',async()=>{
  vi.mocked(readStock).mockResolvedValue({revision:0,items:[data.items[0],{id:'vac',name:'Пылесос T8',category:'Техника',unit:'шт',note:'',adler:1,sochi:1,targetAdler:2,targetSochi:1}],history:[]});
  sessionStorage.setItem('sklad-session',JSON.stringify({token:'test',actor:'Тест'}));
  mount();
  await screen.findByText('Ведро');
  expect(screen.getByRole('columnheader',{name:/норма, не факт/})).toBeInTheDocument();
  expect(screen.getByText(/отдельно от факта/)).toBeInTheDocument();
  fireEvent.change(screen.getByLabelText('Фильтр остатков'),{target:{value:'equipment'}});
  expect(screen.queryByText('Ведро')).not.toBeInTheDocument();
  expect(screen.getByText('Пылесос T8')).toBeInTheDocument();
  expect(screen.getByText(/Эталон техники: в столбце/)).toBeInTheDocument();
});
it('shows a repair badge and keeps the counted quantity',async()=>{
  vi.mocked(readStock).mockResolvedValue({...data,items:[{...data.items[0],note:'держать на складе, ремонт'}]});
  sessionStorage.setItem('sklad-session',JSON.stringify({token:'test',actor:'Тест'}));
  mount();
  await screen.findByText('Ведро');
  expect(screen.getAllByText('В ремонте').some(el=>el.classList.contains('badge-repair'))).toBe(true);
  expect(screen.getByText('7')).toBeInTheDocument();
});
it('deletes an item after confirmation',async()=>{
  sessionStorage.setItem('sklad-session',JSON.stringify({token:'test',actor:'Тест'}));
  vi.mocked(rpc).mockResolvedValue({...data,items:[],revision:1});
  mount();
  await screen.findByText('Ведро');
  fireEvent.click(screen.getByRole('button',{name:'Удалить: Ведро'}));
  fireEvent.change(screen.getByLabelText('Основание / комментарий'),{target:{value:'Непосчитанная заглушка'}});
  fireEvent.click(screen.getByRole('checkbox',{name:'Подтверждаю безвозвратное удаление'}));
  fireEvent.click(screen.getByText('Удалить безвозвратно'));
  await waitFor(()=>expect(rpc).toHaveBeenCalled());
  expect(vi.mocked(rpc).mock.calls[0][0]).toBe('command');
  expect(vi.mocked(rpc).mock.calls[0][1]).toMatchObject({p_token:'test',p_revision:0,p_command:{kind:'delete',id:'bucket',note:'Непосчитанная заглушка'}});
});
it('appends a repair note through annotate without sending a quantity',async()=>{
  vi.mocked(readStock).mockResolvedValue({...data,items:[{...data.items[0],note:'эталон Адлер'}]});
  sessionStorage.setItem('sklad-session',JSON.stringify({token:'test',actor:'Тест'}));
  vi.mocked(rpc).mockResolvedValue({...data,revision:1});
  mount();
  await screen.findByText('Ведро');
  fireEvent.click(screen.getByRole('button',{name:'Примечание: Ведро'}));
  fireEvent.click(screen.getByRole('button',{name:'Добавить «В ремонте.»'}));
  fireEvent.change(screen.getByLabelText('Основание / комментарий'),{target:{value:'Отметили ремонт'}});
  fireEvent.click(screen.getByText('Сохранить примечание'));
  await waitFor(()=>expect(rpc).toHaveBeenCalled());
  expect(vi.mocked(rpc).mock.calls[0][1]).toMatchObject({p_token:'test',p_revision:0,p_command:{kind:'annotate',id:'bucket',note:'Отметили ремонт',itemNote:'эталон Адлер В ремонте.'}});
  expect(vi.mocked(rpc).mock.calls[0][1].p_command).not.toHaveProperty('lines');
});
it('hides zero fact on the selected warehouse until the toggle is off',async()=>{
  vi.mocked(readStock).mockResolvedValue({revision:0,items:[
    {id:'mop',name:'Швабра',category:'Инвентарь',unit:'шт',note:'',adler:0,sochi:0,targetAdler:2,targetSochi:null},
    {id:'sponge',name:'Губка',category:'Инвентарь',unit:'шт',note:'',adler:1,sochi:4,targetAdler:4,targetSochi:4},
    {id:'vac',name:'Пылесос',category:'Техника',unit:'шт',note:'',adler:1,sochi:0,targetAdler:1,targetSochi:null},
    {id:'acid',name:'Кислота',category:'Химия',unit:'л',note:'',adler:null,sochi:0,targetAdler:null,targetSochi:null},
  ],history:[]});
  sessionStorage.setItem('sklad-session',JSON.stringify({token:'test',actor:'Тест'}));
  mount();
  await screen.findByText('Губка');
  const toggle = screen.getByRole('checkbox',{name:'Скрыть нули'});
  expect(toggle).toBeChecked();
  expect(screen.queryByText('Швабра')).not.toBeInTheDocument();
  expect(screen.getByText('Пылесос')).toBeInTheDocument();
  expect(screen.getByText('Кислота')).toBeInTheDocument();
  fireEvent.change(screen.getByLabelText('Фильтр остатков'),{target:{value:'short'}});
  expect(screen.getByText('Губка')).toBeInTheDocument();
  expect(screen.queryByText('Швабра')).not.toBeInTheDocument();
  expect(screen.queryByText('Пылесос')).not.toBeInTheDocument();
  fireEvent.change(screen.getByLabelText('Фильтр остатков'),{target:{value:'unknown'}});
  expect(screen.getByText('Кислота')).toBeInTheDocument();
  expect(screen.queryByText('Швабра')).not.toBeInTheDocument();
  expect(screen.queryByText('Губка')).not.toBeInTheDocument();
  fireEvent.change(screen.getByLabelText('Фильтр остатков'),{target:{value:'equipment'}});
  expect(screen.getByText('Пылесос')).toBeInTheDocument();
  expect(screen.queryByText('Швабра')).not.toBeInTheDocument();
  fireEvent.change(screen.getByLabelText('Фильтр остатков'),{target:{value:'all'}});
  fireEvent.change(screen.getByLabelText('Категория'),{target:{value:'Техника'}});
  expect(screen.getByText('Пылесос')).toBeInTheDocument();
  expect(screen.queryByText('Губка')).not.toBeInTheDocument();
  fireEvent.change(screen.getByLabelText('Категория'),{target:{value:''}});
  fireEvent.click(screen.getByText('К пополнению'));
  expect(screen.getByText('Губка')).toBeInTheDocument();
  expect(screen.queryByText('Швабра')).not.toBeInTheDocument();
  fireEvent.click(toggle);
  expect(toggle).not.toBeChecked();
  expect(screen.getByText('Швабра')).toBeInTheDocument();
  expect(screen.getByText('Губка')).toBeInTheDocument();
  fireEvent.click(toggle);
  fireEvent.click(screen.getByText('Остатки'));
  fireEvent.click(screen.getByRole('button',{name:'Сочи'}));
  expect(screen.getByText('Губка')).toBeInTheDocument();
  expect(screen.queryByText('Швабра')).not.toBeInTheDocument();
  expect(screen.queryByText('Пылесос')).not.toBeInTheDocument();
  expect(screen.queryByText('Кислота')).not.toBeInTheDocument();
  fireEvent.click(toggle);
  expect(screen.getByText('Швабра')).toBeInTheDocument();
  expect(screen.getByText('Пылесос')).toBeInTheDocument();
  expect(screen.getByText('Кислота')).toBeInTheDocument();
});
